// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg8oTxsmNGx7pbV2-vx_-RZC3lihMnd7o',
    appId: '1:387082872753:web:a679d2190fc77f18313f90',
    messagingSenderId: '387082872753',
    projectId: 'roomates-fe712',
    authDomain: 'roomates-fe712.firebaseapp.com',
    databaseURL: 'https://roomates-fe712-default-rtdb.firebaseio.com',
    storageBucket: 'roomates-fe712.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJVFPvO9lIILxvhLPwlr-XCm9NNF_AAI',
    appId: '1:387082872753:android:e12cb0130f3a236c313f90',
    messagingSenderId: '387082872753',
    projectId: 'roomates-fe712',
    databaseURL: 'https://roomates-fe712-default-rtdb.firebaseio.com',
    storageBucket: 'roomates-fe712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBGf8oL_wktmUbbn8goRY0zsmH9R8NEjo',
    appId: '1:387082872753:ios:55d1ec112b2077f6313f90',
    messagingSenderId: '387082872753',
    projectId: 'roomates-fe712',
    databaseURL: 'https://roomates-fe712-default-rtdb.firebaseio.com',
    storageBucket: 'roomates-fe712.appspot.com',
    androidClientId: '387082872753-2oa9kk4hd49842nddfrj21fgffg07cka.apps.googleusercontent.com',
    iosClientId: '387082872753-8m5f2pr2uokjjrv7i7ddo8li3av0gj7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBGf8oL_wktmUbbn8goRY0zsmH9R8NEjo',
    appId: '1:387082872753:ios:b0a0ab0f83039f53313f90',
    messagingSenderId: '387082872753',
    projectId: 'roomates-fe712',
    databaseURL: 'https://roomates-fe712-default-rtdb.firebaseio.com',
    storageBucket: 'roomates-fe712.appspot.com',
    androidClientId: '387082872753-2oa9kk4hd49842nddfrj21fgffg07cka.apps.googleusercontent.com',
    iosClientId: '387082872753-3vhg5rccfo0r8i3n8hdrrpou1q2ikt39.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomates.RunnerTests',
  );
}
